"""Display stack contract: monitors.conf loading, guarding and rotated geometry.

Everything runs against temporary HOMEs, fake Hyprland bindings and stub
commands; nothing reads or changes the live desktop.
"""

import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import textwrap
import unittest


ROOT = Path(__file__).resolve().parents[1]
NEEDS_LUA = unittest.skipUnless(shutil.which("lua"), "Lua runtime unavailable")
NEEDS_JQ = unittest.skipUnless(shutil.which("jq"), "jq unavailable")
HYPR = ROOT / "src/compositors/hyprland/hypr"
BIN = ROOT / "src/shared/bin"

LUA_ENCODER = r'''
local function str(s)
    return '"' .. s:gsub('[%c"\\]', function(c)
        return string.format("\\u%04x", c:byte())
    end) .. '"'
end
function encode(v)
    local t = type(v)
    if t == "table" then
        local keys = {}
        for k in pairs(v) do keys[#keys + 1] = k end
        table.sort(keys)
        local parts = {}
        for _, k in ipairs(keys) do parts[#parts + 1] = str(k) .. ":" .. encode(v[k]) end
        return "{" .. table.concat(parts, ",") .. "}"
    elseif t == "number" then
        return "[" .. str(math.type(v)) .. "," .. string.format("%.17g", v) .. "]"
    elseif t == "string" then
        return '["string",' .. str(v) .. "]"
    end
    return "[" .. str(t) .. "," .. tostring(v) .. "]"
end
'''

LOADER_HARNESS = LUA_ENCODER + r'''
package.path = arg[1] .. "/?.lua;" .. package.path
hl = {monitor = function(spec)
    if spec.output == "explode" then error("rejected by fake hl") end
    io.write("CALL ", encode(spec), "\n")
end}
local real_print = print
print = function(...) io.write("LOG ", table.concat({...}, " "), "\n") end
require("monitors_loader").load(arg[2])
'''


def plain(value):
    """Turn the typed Lua encoding into Python values."""
    if isinstance(value, dict):
        return {key: plain(item) for key, item in value.items()}
    kind, item = value
    return item


def lua(script, *args, timeout=5):
    result = subprocess.run(["lua", "-", *map(str, args)], input=script,
                            text=True, capture_output=True, timeout=timeout)
    if result.returncode:
        raise AssertionError(result.stderr)
    return result.stdout


@NEEDS_LUA
class MonitorsLoaderTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.conf = Path(self.temp.name) / "monitors.conf"

    def load(self, text):
        self.conf.write_bytes(textwrap.dedent(text).encode())
        calls, logs = [], []
        for line in lua(LOADER_HARNESS, HYPR, self.conf).splitlines():
            kind, _, payload = line.partition(" ")
            if kind == "CALL":
                calls.append(json.loads(payload))
            else:
                logs.append(payload)
        return calls, logs

    def specs(self, text):
        return [plain(call) for call in self.load(text)[0]]

    def test_settings_lines_keep_exact_values(self):
        calls, logs = self.load("""\
            # Generated by settings
            monitor = HDMI-A-1, 2560x1440@59.95, 0x0, 1.00, transform, 0
            monitor = desc:Dell Inc. DELL P2412H KG49T35D59GU, 1920x1080@60.00, 2560x0, 1.333333, transform, 1
            """)
        self.assertEqual(logs, [])
        self.assertEqual([plain(call) for call in calls], [
            {"output": "HDMI-A-1", "mode": "2560x1440@59.95", "position": "0x0",
             "scale": 1.0, "transform": 0, "disabled": False},
            {"output": "desc:Dell Inc. DELL P2412H KG49T35D59GU", "mode": "1920x1080@60.00",
             "position": "2560x0", "scale": 1.333333, "transform": 1, "disabled": False},
        ])
        # Hyprland's integer fields reject Lua floats and strings.
        self.assertEqual(calls[1]["transform"][0], "integer")

    def test_inline_comments_follow_hyprlang(self):
        specs = self.specs("""\
            monitor = DP-3, 1920x1080@60, 2560x0, 1, transform, 1 # portrait
            ## a comment even when doubled
            monitor = Odd##Name, preferred, auto, 1 # trailing
            monitor = Three###Hashes, preferred, auto, 1
            """)
        self.assertEqual([spec["output"] for spec in specs], ["DP-3", "Odd#Name", "Three##Hashes"])
        self.assertEqual(specs[0]["transform"], 1)

    def test_disable_aliases_and_full_line_reenables(self):
        specs = self.specs("""\
            monitor = eDP-1, disabled
            monitor = HDMI-A-1, disable
            monitor = HDMI-A-1, 2560x1440@60, 0x0, 1
            """)
        self.assertEqual(specs, [
            {"output": "eDP-1", "disabled": True},
            {"output": "HDMI-A-1", "mode": "2560x1440@60", "position": "0x0", "scale": 1,
             "transform": 0, "disabled": False},
        ])

    def test_later_full_line_starts_from_defaults(self):
        specs = self.specs("""\
            monitor = DP-3, 1920x1080@60, 0x0, 1, transform, 1, vrr, 1
            monitor = DP-3, 1920x1080@60, 0x0, 1
            """)
        self.assertEqual(specs, [{"output": "DP-3", "mode": "1920x1080@60", "position": "0x0",
                                  "scale": 1, "transform": 0, "disabled": False}])

    def test_standalone_transform_matches_hyprlang(self):
        specs, logs = self.load("""\
            monitor = DP-3, 1920x1080@60, 0x0, 1
            monitor = HDMI-A-1, 2560x1440@60, 1080x0, 1
            monitor = DP-3, transform, 3
            monitor = eDP-1, transform, 1
            monitor = HDMI-A-1, transform, 9
            """)
        specs = [plain(spec) for spec in specs]
        # The modified rule moves after HDMI-A-1, as hyprlang re-adds it.
        self.assertEqual([spec["output"] for spec in specs], ["HDMI-A-1", "DP-3"])
        self.assertEqual(specs[1]["transform"], 3)
        self.assertEqual(specs[0]["transform"], 0)
        self.assertEqual(len(logs), 2)
        self.assertIn("eDP-1", logs[0])
        self.assertIn("invalid transform", logs[1])

    def test_catch_all_transform_modifies_the_built_in_fallback(self):
        # hyprland.lua and hyprland.conf both define the catch-all first, so
        # hyprlang finds it; the loader must merge into it the same way.
        self.assertEqual(self.specs("monitor = , transform, 1\n"), [{"output": "", "transform": 1}])

    def test_numeric_scale_spellings_are_normalised(self):
        specs = self.specs("""\
            monitor = DP-1, preferred, auto, .5
            monitor = DP-2, preferred, auto, 2.
            monitor = DP-3, preferred, auto, auto
            monitor = DP-4, preferred, auto,
            """)
        self.assertEqual([spec["scale"] for spec in specs], [0.5, 2.0, "auto", ""])

    def test_addreserved_modifies_in_place_or_creates_rule(self):
        specs, logs = self.load("""\
            monitor = DP-3, 1920x1080@60, 0x0, 1
            monitor = HDMI-A-1, 2560x1440@60, 1920x0, 1
            monitor = DP-3, addreserved, 40, 0, 0, 0
            monitor = DP-9, addreserved, 0, 10, 20, 30
            monitor = DP-8, addreserved, x, 0, 0, 0
            """)
        specs = [plain(spec) for spec in specs]
        self.assertEqual([spec["output"] for spec in specs], ["DP-3", "HDMI-A-1", "DP-9"])
        self.assertEqual(specs[0]["reserved"], {"top": 40, "bottom": 0, "left": 0, "right": 0})
        self.assertEqual(specs[2], {"output": "DP-9",
                                    "reserved": {"top": 0, "bottom": 10, "left": 20, "right": 30}})
        self.assertEqual(len(logs), 1)

    def test_extra_options_are_typed_and_stop_at_empty_field(self):
        calls, _ = self.load("""\
            monitor = DP-1, 3840x2160@144, 0x0, 1.5, vrr, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, mirror, DP-2
            monitor = DP-2, preferred, auto, auto, , transform, 1
            """)
        first, second = calls
        self.assertEqual(plain(first), {
            "output": "DP-1", "mode": "3840x2160@144", "position": "0x0", "scale": 1.5,
            "transform": 0, "disabled": False, "vrr": 1, "bitdepth": 10, "cm": "hdr",
            "sdrbrightness": 1.2, "mirror": "DP-2"})
        self.assertEqual(first["vrr"][0], "integer")
        self.assertEqual(first["sdrbrightness"][0], "float")
        self.assertEqual(plain(second)["transform"], 0)

    def test_invalid_or_unknown_options_are_skipped_not_sent_to_hyprland(self):
        calls, logs = self.load("""\
            monitor = DP-3, 1920x1080@60, 0x0, 1, transform, sideways, vrr, 9, cm, neon, vrrr, 1, icc, , bitdepth, 10
            monitor = HDMI-A-1, 2560x1440@60, 1920x0, 1, transform, 1.0, sdrbrightness, bright
            """)
        # Like hyprlang, an empty value is rejected but reading continues; only
        # an empty KEY ends the option list.
        self.assertEqual([plain(call) for call in calls], [
            {"output": "DP-3", "mode": "1920x1080@60", "position": "0x0", "scale": 1,
             "transform": 0, "disabled": False, "bitdepth": 10},
            {"output": "HDMI-A-1", "mode": "2560x1440@60", "position": "1920x0", "scale": 1,
             "transform": 0, "disabled": False},
        ])
        self.assertEqual(sum("skipped invalid option" in log for log in logs), 7)

    def test_last_definition_order_and_catch_all(self):
        specs = self.specs("""\
            monitor = , preferred, auto, 1.5
            monitor = DP-3, 1920x1080@60, 0x0, 1
            monitor = desc:Dell Inc. DELL, 1920x1080@60, 0x0, 1, transform, 1
            monitor = DP-3, disable
            """)
        self.assertEqual([spec["output"] for spec in specs], ["", "desc:Dell Inc. DELL", "DP-3"])

    def test_crlf_and_garbage_lines_do_not_stop_loading(self):
        self.conf.write_bytes(b"monitor = DP-3, 1920x1080@60, 0x0, 1, transform, 1\r\n"
                              b"not a monitor line\r\nmonitor = explode, preferred, auto, 1\r\n"
                              b"monitor = HDMI-A-1, preferred, auto, 1\r\n")
        out = lua(LOADER_HARNESS, HYPR, self.conf)
        calls = [plain(json.loads(line[5:])) for line in out.splitlines() if line.startswith("CALL ")]
        self.assertEqual([call["output"] for call in calls], ["DP-3", "HDMI-A-1"])
        self.assertEqual(calls[0]["transform"], 1)
        self.assertIn("explode", out)

    def test_missing_file_is_silent(self):
        self.assertEqual(lua(LOADER_HARNESS, HYPR, self.conf.with_name("absent.conf")), "")


class EntryPointTests(unittest.TestCase):
    @NEEDS_LUA
    def test_loader_failure_cannot_abort_the_lua_config(self):
        harness = r'''
local root = arg[1]
package.path = root .. "/?.lua;" .. package.path
package.preload.monitors_loader = function()
    return {load = function() error("broken loader") end}
end
for _, name in ipairs({"workspace_policy", "envs", "input", "looknfeel", "windows",
                       "aspect_column", "popup_watchers", "apps", "autostart"}) do
    package.preload[name] = function() return {} end
end
package.preload.bindings_loader = function() return {load = function() end} end
package.preload["opacity-policy"] = function() print("REACHED END") return {} end
hl = {monitor = function() end}
local getenv = os.getenv
os.getenv = function(name) if name == "HOME" then return "/nonexistent-fixture-home" end return getenv(name) end
dofile(root .. "/hyprland.lua")
'''
        out = lua(harness, HYPR)
        self.assertIn("monitors_loader failed", out)
        self.assertIn("REACHED END", out)

    def test_hyprlang_catch_all_precedes_saved_layout(self):
        lines = [line.strip() for line in (HYPR / "hyprland.conf").read_text().splitlines()]
        self.assertLess(lines.index("monitor = , preferred, auto, auto"),
                        lines.index("source = ~/.config/hypr/monitors.conf"))


class MonitorsGuardTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.home = Path(self.temp.name)
        self.hypr = self.home / ".config/hypr"
        self.hypr.mkdir(parents=True)
        self.conf = self.hypr / "monitors.conf"
        self.drm = self.home / "drm"

    def connect(self, *names, disconnected=()):
        for name, status in [(n, "connected") for n in names] + [(n, "disconnected") for n in disconnected]:
            folder = self.drm / f"card1-{name}"
            folder.mkdir(parents=True)
            (folder / "status").write_text(status + "\n")

    def run_guard(self):
        env = dict(os.environ, HOME=str(self.home), XDG_CACHE_HOME=str(self.home / "cache"),
                   SMPLOS_DRM_SYSFS=str(self.drm))
        subprocess.run(["bash", str(BIN / "monitors-guard")], env=env, check=True, timeout=10)
        return (self.home / "cache/smplos/monitors-guard.log").read_text()

    def test_valid_layout_is_kept_and_snapshotted(self):
        self.connect("DP-3", "HDMI-A-1")
        text = "monitor = HDMI-A-1, 2560x1440@59.95, 0x0, 1.00, transform, 0\n" \
               "monitor = desc:Dell Inc. DELL P2412H KG49T35D59GU, 1920x1080@60.00, 2560x0, 1, transform, 1\n"
        self.conf.write_text(text)
        self.run_guard()
        self.assertEqual(self.conf.read_text(), text)
        self.assertEqual((self.hypr / "monitors.conf.last-known-good").read_text(), text)

    def test_intentionally_disabled_laptop_panel_is_kept(self):
        self.connect("eDP-1", "DP-3")
        text = "monitor = eDP-1, disabled # lid closed\n"
        self.conf.write_text(text)
        self.assertIn("OK: 0/1", self.run_guard())
        self.assertEqual(self.conf.read_text(), text)

    def test_every_connected_display_disabled_restores_newest_valid_backup(self):
        self.connect("eDP-1", "DP-3", disconnected=("HDMI-A-1",))
        self.conf.write_text("monitor = eDP-1, disable\nmonitor = DP-3, disabled # broken\n"
                             "monitor = DP-3, transform, 1\n")
        older = self.hypr / "monitors.conf.bak-20260101-000000"
        older.write_text("monitor = DP-3, 1920x1080@60, 0x0, 1\n")
        newest_corrupt = self.hypr / "monitors.conf.bak-20260102-000000"
        newest_corrupt.write_text("monitor = DP-3, disable\nmonitor = eDP-1, disable\n")
        os.utime(older, (1, 1))
        log = self.run_guard()
        self.assertIn("CORRUPT", log)
        self.assertEqual(self.conf.read_text(), older.read_text())

    def test_unverifiable_all_disabled_file_is_moved_aside_without_backup(self):
        self.connect("DP-3")
        self.conf.write_text("monitor = desc:Dell Inc. DELL P2412H, disable\n")
        self.run_guard()
        self.assertFalse(self.conf.exists())
        self.assertEqual(len(list(self.hypr.glob("monitors.conf.corrupt-*"))), 1)

    def test_comment_only_file_is_left_alone(self):
        self.conf.write_text("# Generated by settings\n")
        self.assertIn("zero monitor rules", self.run_guard())
        self.assertTrue(self.conf.exists())


@NEEDS_JQ
class RotatedGeometryTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        bin_dir = self.root / "bin"
        bin_dir.mkdir()
        self.calls = self.root / "calls"
        hyprctl = bin_dir / "hyprctl"
        hyprctl.write_text(textwrap.dedent("""\
            #!/usr/bin/env python3
            import os, sys
            args = sys.argv[1:]
            if args == ["-j", "clients"]:
                print(os.environ["CLIENTS"])
            elif args == ["-j", "monitors"]:
                print(os.environ["MONITORS"])
            else:
                with open(os.environ["CALLS"], "a") as out:
                    out.write(" ".join(args) + "\\n")
            """))
        hyprctl.chmod(0o755)
        self.env = dict(os.environ, PATH=f"{bin_dir}:{os.environ['PATH']}", CALLS=str(self.calls),
                        XDG_CONFIG_HOME=str(self.root / "config"),
                        MONITORS=json.dumps([
                            {"id": 0, "x": 0, "y": 0, "width": 2560, "height": 1440, "scale": 1.0, "transform": 0},
                            {"id": 1, "x": 2560, "y": 0, "width": 1920, "height": 1080, "scale": 1.0, "transform": 1},
                        ]))

    def snap(self, x, y, w, h, monitor=1, **env):
        clients = [{"address": "0xabc", "floating": True, "workspace": {"id": 2}, "fullscreen": 0,
                    "at": [x, y], "size": [w, h], "monitor": monitor}]
        script = f'source "{BIN / "window-guard"}"\nsnap_window 0xabc\n'
        self.calls.unlink(missing_ok=True)
        subprocess.run(["bash", "-c", script], env=dict(self.env, CLIENTS=json.dumps(clients), **env),
                       check=True, timeout=10)
        return self.calls.read_text() if self.calls.exists() else ""

    def test_window_inside_portrait_monitor_is_not_moved(self):
        self.assertEqual(self.snap(2700, 1000, 800, 600), "")

    def test_window_past_portrait_right_edge_is_pulled_back(self):
        self.assertIn("x=3240, y=100", self.snap(3400, 100, 400, 300))

    def test_two_decimal_scale_recovers_the_exact_logical_size(self):
        # 2880x1800 at 135/120 is 2560x1600 logical; hyprctl prints 1.12.
        panel = json.dumps([{"id": 0, "x": 0, "y": 0, "width": 2880, "height": 1800,
                             "scale": 1.12, "transform": 0}])
        self.assertEqual(self.snap(2160, 0, 400, 300, monitor=0, MONITORS=panel), "")
        self.assertIn("x=2160, y=0", self.snap(2175, 0, 400, 300, monitor=0, MONITORS=panel))

    @NEEDS_LUA
    def test_aspect_column_treats_mirrored_rotation_as_portrait(self):
        harness = r'''
package.path = arg[1] .. "/?.lua;" .. package.path
local handlers, widths = {}, {}
local transform = tonumber(arg[2])
hl = {
    on = function(name, fn) handlers[name] = fn end,
    config = function(t) widths[#widths + 1] = t.scrolling.column_width end,
    get_active_monitor = function() return {width = 3440, height = 1440, transform = transform} end,
}
require("aspect_column")
handlers["config.reloaded"]()
print(widths[#widths])
'''
        self.assertEqual(lua(harness, HYPR, 4).strip(), "0.65")
        self.assertEqual(lua(harness, HYPR, 5).strip(), "0.95")


if __name__ == "__main__":
    unittest.main()
