/* smplOS nemo theme — auto-generated by theme-set / generate-theme-configs.sh */
/* Do not edit manually. */

/* =====================================================================
 * GTK named-color overrides (used by nemo's own bundled fallback CSS)
 * These must be defined at GTK_STYLE_PROVIDER_PRIORITY_USER so they
 * shadow the active Adwaita definitions inside nemo's widget rules.
 * ===================================================================== */

@define-color theme_selected_bg_color {{ selection_background }};
@define-color theme_selected_fg_color {{ selection_foreground }};
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_unfocused_bg_color {{ bg_light }};
@define-color theme_unfocused_selected_bg_color alpha({{ selection_background }}, 0.35);
@define-color borders {{ bg_lighter }};

/* =====================================================================
 * Main window chrome
 * ===================================================================== */

.nemo-window,
.nemo-window:backdrop {
    background-color: {{ background }};
    color: {{ foreground }};
}

/* =====================================================================
 * Menu bar (File / Edit / View …)
 * Lock bg to theme background in both focused and backdrop (unfocused)
 * states — Adwaita sets menubar:backdrop to a grey that differs from bg.
 * ===================================================================== */

menubar,
menubar:backdrop {
    background-color: {{ background }};
    background-image: none;
    color: {{ foreground }};
    box-shadow: none;
}

/* =====================================================================
 * Bottom status bar — NemoStatusBar extends GtkBox with class "toolbar".
 * Distinct from toolbar.primary-toolbar (the top toolbar).
 * ===================================================================== */

box.toolbar,
box.toolbar:backdrop {
    background-color: {{ background }};
    background-image: none;
    color: {{ foreground }};
    border-top: 1px solid {{ bg_lighter }};
    box-shadow: none;
}

box.toolbar button,
box.toolbar togglebutton {
    color: {{ foreground }};
    background-color: transparent;
    background-image: none;
    border: none;
    box-shadow: none;
}

box.toolbar button:hover,
box.toolbar togglebutton:hover {
    background-color: alpha({{ foreground }}, 0.1);
    color: {{ foreground }};
}

box.toolbar button:checked,
box.toolbar togglebutton:checked,
box.toolbar button:active,
box.toolbar togglebutton:active {
    background-color: alpha({{ selection_background }}, 0.25);
    background-image: none;
    color: {{ foreground }};
    box-shadow: none;
}

/* =====================================================================
 * Toolbar
 * ===================================================================== */

toolbar.primary-toolbar,
toolbar.primary-toolbar:backdrop {
    background-color: {{ background }};
    background-image: none;
    color: {{ foreground }};
    border-bottom: 1px solid {{ bg_lighter }};
    box-shadow: none;
}

toolbar.primary-toolbar button,
toolbar.primary-toolbar button.flat {
    color: {{ foreground }};
    background-color: transparent;
    border: none;
    box-shadow: none;
}

toolbar.primary-toolbar button:hover,
toolbar.primary-toolbar button.flat:hover {
    background-color: alpha({{ foreground }}, 0.1);
    color: {{ foreground }};
}

toolbar.primary-toolbar button:checked,
toolbar.primary-toolbar button:active,
toolbar.primary-toolbar button.active,
toolbar.primary-toolbar button.suggested-action {
    /* Subtle tint only — keep icon at fg so symbols remain visible */
    background-color: alpha({{ selection_background }}, 0.25);
    color: {{ foreground }};
}

toolbar.primary-toolbar button:checked label,
toolbar.primary-toolbar button:active label,
toolbar.primary-toolbar button.active label,
toolbar.primary-toolbar button.suggested-action label {
    color: {{ foreground }};
}

/* =====================================================================
 * Path / breadcrumb bar
 * ===================================================================== */

.path-bar button {
    color: {{ foreground }};
    background-color: transparent;
    border: none;
    box-shadow: none;
}

/* Match Adwaita .path-bar button label:dir() specificity (0,2,2) */
.path-bar button label:dir(ltr),
.path-bar button label:dir(rtl),
.path-bar button label {
    color: {{ foreground }};
}

.path-bar button:hover {
    background-color: alpha({{ bg_lighter }}, 0.6);
    color: {{ foreground }};
}

.path-bar button:hover label:dir(ltr),
.path-bar button:hover label:dir(rtl),
.path-bar button:hover label {
    color: {{ foreground }};
}

.path-bar button:checked,
.path-bar button:active {
    /* Current directory: subtle tint, keep foreground text colour.
     * background-image: none clears Adwaita's button:checked
     * { background-image: image(#191919) } which paints over bg-color. */
    background-color: alpha({{ selection_background }}, 0.25);
    background-image: none;
    color: {{ foreground }};
    box-shadow: none;
}

.path-bar button:checked label:dir(ltr),
.path-bar button:checked label:dir(rtl),
.path-bar button:active label:dir(ltr),
.path-bar button:active label:dir(rtl),
.path-bar button:checked label,
.path-bar button:active label {
    color: {{ foreground }};
}

/* =====================================================================
 * File list / icon grid view
 * ===================================================================== */

.nemo-window .view,
.nemo-window iconview,
.nemo-window .view:backdrop,
.nemo-window iconview:backdrop {
    background-color: {{ background }};
    color: {{ foreground }};
}

.nemo-window .view:selected,
.nemo-window iconview:selected {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

.nemo-window .view:selected label,
.nemo-window .view:selected *,
.nemo-window iconview:selected label,
.nemo-window iconview:selected * {
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Inactive F3 pane (split view) — same background as active pane;
 * selected item gets an outline ring instead of a filled highlight.
 * ===================================================================== */

.nemo-window .nemo-inactive-pane .view:not(:selected),
.nemo-window .nemo-inactive-pane .view:backdrop:not(:selected),
.nemo-window .nemo-inactive-pane iconview,
.nemo-window .nemo-inactive-pane iconview:backdrop {
    background-color: {{ background }};
}

.nemo-window .nemo-inactive-pane .view:selected {
    background-color: transparent;
    color: {{ foreground }};
    outline: 2px dotted {{ selection_background }};
    outline-offset: -2px;
}

.nemo-window .nemo-inactive-pane .view:selected label,
.nemo-window .nemo-inactive-pane .view:selected * {
    color: {{ foreground }};
}

/* =====================================================================
 * Places sidebar
 * ===================================================================== */

.sidebar,
.sidebar:backdrop,
.places-treeview,
.places-treeview:backdrop {
    background-color: {{ bg_light }};
    color: {{ foreground }};
}

.sidebar row:selected,
.places-treeview:selected {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

.sidebar row:selected label,
.sidebar row:selected *,
.places-treeview:selected label,
.places-treeview:selected * {
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Rename / inline-entry box inside icon view
 * ===================================================================== */

.nemo-window .nemo-window-pane widget.entry {
    border-color: {{ accent }};
    background-color: {{ bg_light }};
    color: {{ foreground }};
}

.nemo-window .nemo-window-pane widget.entry:selected {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
    border-color: {{ foreground }};
}

/* =====================================================================
 * Floating status bar (replaces the traditional status bar)
 * ===================================================================== */

.floating-bar {
    background-color: {{ foreground }};
    color: {{ background }};
    border-color: {{ foreground }};
}

/* =====================================================================
 * Drop bar (drag-over top bar)
 * ===================================================================== */

#drop-bar > revealer > box {
    background-color: {{ bg_light }};
    border-bottom-color: {{ bg_lighter }};
}

/* =====================================================================
 * Desktop icon labels
 * ===================================================================== */

.nemo-desktop.nemo-canvas-item {
    color: {{ foreground }};
}

.nemo-desktop.nemo-canvas-item:selected {
    background-color: alpha({{ selection_background }}, 0.8);
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Search bar
 * ===================================================================== */

searchbar,
searchbar entry {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
}

/* =====================================================================
 * Popup menus (e.g. bookmark picker)
 * ===================================================================== */

menu {
    background-color: {{ background }};
    color: {{ foreground }};
    border: 1px solid {{ bg_lighter }};
}

menuitem {
    color: {{ foreground }};
}

/* Match Adwaita's exact selector specificity (0,1,3) so we always win */
menu menuitem label:dir(ltr),
menu menuitem label:dir(rtl),
.menu menuitem label:dir(ltr),
.menu menuitem label:dir(rtl),
.context-menu menuitem label:dir(ltr),
.context-menu menuitem label:dir(rtl),
menuitem label {
    color: {{ foreground }};
}

/* Menubar top-level items (Files, Edit, View…) */
menubar > menuitem,
menubar > menuitem:backdrop {
    color: {{ foreground }};
    box-shadow: none;
}

menubar > menuitem:hover {
    background-color: alpha({{ foreground }}, 0.1);
    color: {{ foreground }};
    box-shadow: none;
}

menuitem:hover {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

menuitem:hover label,
menu menuitem:hover label:dir(ltr),
menu menuitem:hover label:dir(rtl),
menuitem:hover * {
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Tooltips
 * ===================================================================== */

tooltip,
tooltip.background {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
    border: 1px solid {{ accent }};
    border-radius: 4px;
    padding: 4px 8px;
}

tooltip label,
tooltip .label {
    color: {{ foreground }};
}

/* =====================================================================
 * modelbutton — used by GtkPopoverMenu (dropdown / hamburger menus)
 * ===================================================================== */

modelbutton {
    background-color: transparent;
    color: {{ foreground }};
}

modelbutton label {
    color: {{ foreground }};
}

modelbutton:hover,
modelbutton:focus {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
    outline: none;
}

modelbutton:hover label,
modelbutton:hover *,
modelbutton:focus label,
modelbutton:focus * {
    color: {{ selection_foreground }};
}

modelbutton:selected {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

modelbutton:selected label,
modelbutton:selected * {
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Listbox rows (used in settings/preferences panels)
 * ===================================================================== */

listbox {
    background-color: {{ background }};
    color: {{ foreground }};
}

listbox row {
    background-color: transparent;
    color: {{ foreground }};
}

listbox row:hover {
    background-color: alpha({{ selection_background }}, 0.3);
    color: {{ foreground }};
}

listbox row:selected,
listbox row:selected:hover {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

listbox row:selected label,
listbox row:selected *,
listbox row:selected:hover label,
listbox row:selected:hover * {
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Text / cursor selection highlight
 * ===================================================================== */

selection {
    background-color: alpha({{ selection_background }}, 0.6);
    color: {{ selection_foreground }};
}

/* Focus outlines */
button:focus,
entry:focus,
treeview:focus,
combobox:focus {
    outline-color: {{ foreground }};
}

/* Combobox popup rows */
combobox > window > frame > scrolledwindow > treeview row:hover,
combobox > window > frame > scrolledwindow > treeview row:selected {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

combobox > window > frame > scrolledwindow > treeview row:hover label,
combobox > window > frame > scrolledwindow > treeview row:hover *,
combobox > window > frame > scrolledwindow > treeview row:selected label,
combobox > window > frame > scrolledwindow > treeview row:selected * {
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Dialogs and secondary windows (preferences, properties, about)
 * ===================================================================== */

dialog,
messagedialog,
window.background {
    background-color: {{ background }};
    color: {{ foreground }};
}

dialog .dialog-vbox,
messagedialog .dialog-vbox {
    background-color: {{ background }};
    color: {{ foreground }};
}

dialog headerbar,
messagedialog headerbar {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
}

/* Scoped to dialogs/popovers so toolbar buttons keep their own hover */
dialog button,
messagedialog button,
.preferences button,
popover button {
    background-color: {{ bg_light }};
    background-image: none;
    color: {{ foreground }};
    border: 1px solid {{ bg_lighter }};
}

dialog button:focus,
messagedialog button:focus,
.preferences button:focus,
popover button:focus,
dialog button:active,
messagedialog button:active,
.preferences button:active,
popover button:active,
dialog button:checked,
messagedialog button:checked,
dialog button.default,
messagedialog button.default {
    background-color: {{ bg_lighter }};
    background-image: none;
    color: {{ foreground }};
    box-shadow: none;
}

dialog button:focus label,
dialog button:focus *,
messagedialog button:focus label,
messagedialog button:focus *,
dialog button:active label,
dialog button:active *,
messagedialog button:active label,
messagedialog button:active *,
dialog button.default label,
messagedialog button.default label {
    color: {{ foreground }};
}

dialog button:hover,
messagedialog button:hover,
.preferences button:hover,
popover button:hover {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

dialog button:hover label,
dialog button:hover *,
messagedialog button:hover label,
messagedialog button:hover *,
.preferences button:hover label,
.preferences button:hover *,
popover button:hover label,
popover button:hover * {
    color: {{ selection_foreground }};
}

dialog button.suggested-action,
messagedialog button.suggested-action {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

dialog button.suggested-action label,
dialog button.suggested-action *,
messagedialog button.suggested-action label,
messagedialog button.suggested-action * {
    color: {{ selection_foreground }};
}

/* Notebook tabs (preferences, properties) */
notebook header {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
}

notebook header tab {
    color: {{ foreground }};
}

notebook header tab:checked {
    background-color: {{ background }};
    color: {{ foreground }};
}

notebook > stack {
    background-color: {{ background }};
    color: {{ foreground }};
}

/* Stack switcher (properties dialog tabs) */
stackswitcher button {
    color: {{ foreground }};
    background-color: transparent;
}

stackswitcher button:hover {
    background-color: alpha({{ foreground }}, 0.15);
    color: {{ foreground }};
}

stackswitcher button:checked {
    color: {{ selection_foreground }};
    background-color: {{ selection_background }};
    background-image: none;
    box-shadow: none;
}

stackswitcher button:checked label,
stackswitcher button:checked * {
    color: {{ selection_foreground }};
}

/* Text views (about license, etc.) */
textview,
textview text {
    background-color: {{ background }};
    color: {{ foreground }};
}

/* Entry fields in dialogs */
entry {
    background-color: {{ bg_light }};
    color: {{ foreground }};
    border: 1px solid {{ bg_lighter }};
}

/* Labels */
label {
    color: {{ foreground }};
}

/* Check / radio buttons */
checkbutton label,
radiobutton label {
    color: {{ foreground }};
}

/* Combo boxes */
combobox button {
    background-color: {{ bg_light }};
    color: {{ foreground }};
    border: 1px solid {{ bg_lighter }};
}

/* Tree / list views in preferences */
treeview {
    background-color: {{ background }};
    color: {{ foreground }};
}

treeview:selected {
    background-color: {{ selection_background }};
    color: {{ selection_foreground }};
}

treeview:selected label,
treeview:selected * {
    color: {{ selection_foreground }};
}

/* Frames and separators */
frame > border {
    border-color: {{ bg_lighter }};
}

separator {
    background-color: {{ bg_lighter }};
}

/* Links in about dialog */
*:link,
*:visited {
    color: {{ foreground }};
}

/* =====================================================================
 * Scrollbars
 * ===================================================================== */

scrollbar slider {
    background-color: {{ bg_lighter }};
}

scrollbar slider:hover {
    background-color: {{ selection_background }};
}
