/* smplOS nemo theme — auto-generated by theme-set / generate-theme-configs.sh */
/* Do not edit manually. */

/* =====================================================================
 * GTK named-color overrides (used by nemo's own bundled fallback CSS)
 * These must be defined at GTK_STYLE_PROVIDER_PRIORITY_USER so they
 * shadow the active Adwaita definitions inside nemo's widget rules.
 * ===================================================================== */

@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ selection_foreground }};
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_unfocused_bg_color {{ bg_light }};
@define-color theme_unfocused_selected_bg_color alpha({{ accent }}, 0.35);
@define-color borders {{ bg_lighter }};

/* =====================================================================
 * Main window chrome
 * ===================================================================== */

.nemo-window {
    background-color: {{ background }};
    color: {{ foreground }};
}

/* =====================================================================
 * Header bar / toolbar
 * ===================================================================== */

headerbar,
.header-bar {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
    border-bottom: 1px solid {{ bg_lighter }};
    box-shadow: none;
}

headerbar button:checked,
headerbar button.active,
headerbar button.suggested-action {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Path bar
 * ===================================================================== */

.path-bar button:checked,
.path-bar button:active {
    color: {{ accent }};
    background-color: {{ bg_lighter }};
}

/* =====================================================================
 * File list / icon grid view
 * ===================================================================== */

.nemo-window .view,
.nemo-window iconview {
    background-color: {{ background }};
    color: {{ foreground }};
}

.nemo-window .view:selected,
.nemo-window iconview:selected {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Inactive F3 pane (split view)
 * ===================================================================== */

.nemo-window .nemo-inactive-pane .view:not(:selected),
.nemo-window .nemo-inactive-pane iconview {
    background-color: {{ bg_lighter }};
}

/* =====================================================================
 * Places sidebar
 * ===================================================================== */

.sidebar,
.places-treeview {
    background-color: {{ bg_light }};
    color: {{ foreground }};
}

.sidebar row:selected,
.places-treeview:selected {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Rename / inline-entry box inside icon view
 * ===================================================================== */

.nemo-window .nemo-window-pane widget.entry {
    border-color: {{ accent }};
    background-color: {{ bg_light }};
    color: {{ foreground }};
}

.nemo-window .nemo-window-pane widget.entry:selected {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
    border-color: {{ accent }};
}

/* =====================================================================
 * Floating status bar (replaces the traditional status bar)
 * ===================================================================== */

.floating-bar {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
    border-color: {{ accent }};
}

/* =====================================================================
 * Drop bar (drag-over top bar)
 * ===================================================================== */

#drop-bar > revealer > box {
    background-color: {{ bg_light }};
    border-bottom-color: {{ bg_lighter }};
}

/* =====================================================================
 * Desktop icon labels
 * ===================================================================== */

.nemo-desktop.nemo-canvas-item {
    color: {{ foreground }};
}

.nemo-desktop.nemo-canvas-item:selected {
    background-color: alpha({{ accent }}, 0.8);
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Search bar
 * ===================================================================== */

searchbar,
searchbar entry {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
}

/* =====================================================================
 * Scrollbars
 * ===================================================================== */

scrollbar slider {
    background-color: {{ muted }};
}

scrollbar slider:hover {
    background-color: {{ accent }};
}
