/* smplOS nemo theme — auto-generated by theme-set / generate-theme-configs.sh */
/* Do not edit manually. */

/* =====================================================================
 * GTK named-color overrides (used by nemo's own bundled fallback CSS)
 * These must be defined at GTK_STYLE_PROVIDER_PRIORITY_USER so they
 * shadow the active Adwaita definitions inside nemo's widget rules.
 * ===================================================================== */

@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ selection_foreground }};
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_unfocused_bg_color {{ bg_light }};
@define-color theme_unfocused_selected_bg_color alpha({{ accent }}, 0.35);
@define-color borders {{ bg_lighter }};

/* =====================================================================
 * Main window chrome
 * ===================================================================== */

.nemo-window {
    background-color: {{ background }};
    color: {{ foreground }};
}

/* =====================================================================
 * Toolbar
 * ===================================================================== */

toolbar.primary-toolbar {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
    border-bottom: 1px solid {{ bg_lighter }};
    box-shadow: none;
}

toolbar.primary-toolbar button,
toolbar.primary-toolbar button.flat {
    color: {{ foreground }};
    background-color: transparent;
    border: none;
    box-shadow: none;
}

toolbar.primary-toolbar button:hover,
toolbar.primary-toolbar button.flat:hover {
    background-color: alpha({{ foreground }}, 0.1);
    color: {{ foreground }};
}

toolbar.primary-toolbar button:checked,
toolbar.primary-toolbar button:active,
toolbar.primary-toolbar button.active,
toolbar.primary-toolbar button.suggested-action {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Path bar
 * ===================================================================== */

.path-bar button {
    color: {{ bg_lighter }};
    background-color: transparent;
    border: none;
    box-shadow: none;
}

.path-bar button:hover {
    background-color: alpha({{ bg_lighter }}, 0.1);
    color: {{ bg_lighter }};
}

.path-bar button:checked,
.path-bar button:active {
    color: {{ accent }};
    background-color: {{ bg_lighter }};
}

/* =====================================================================
 * File list / icon grid view
 * ===================================================================== */

.nemo-window .view,
.nemo-window iconview {
    background-color: {{ background }};
    color: {{ foreground }};
}

.nemo-window .view:selected,
.nemo-window iconview:selected {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Inactive F3 pane (split view)
 * ===================================================================== */

.nemo-window .nemo-inactive-pane .view:not(:selected),
.nemo-window .nemo-inactive-pane iconview {
    background-color: {{ bg_lighter }};
}

/* =====================================================================
 * Places sidebar
 * ===================================================================== */

.sidebar,
.places-treeview {
    background-color: {{ bg_light }};
    color: {{ foreground }};
}

.sidebar row:selected,
.places-treeview:selected {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Rename / inline-entry box inside icon view
 * ===================================================================== */

.nemo-window .nemo-window-pane widget.entry {
    border-color: {{ accent }};
    background-color: {{ bg_light }};
    color: {{ foreground }};
}

.nemo-window .nemo-window-pane widget.entry:selected {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
    border-color: {{ accent }};
}

/* =====================================================================
 * Floating status bar (replaces the traditional status bar)
 * ===================================================================== */

.floating-bar {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
    border-color: {{ accent }};
}

/* =====================================================================
 * Drop bar (drag-over top bar)
 * ===================================================================== */

#drop-bar > revealer > box {
    background-color: {{ bg_light }};
    border-bottom-color: {{ bg_lighter }};
}

/* =====================================================================
 * Desktop icon labels
 * ===================================================================== */

.nemo-desktop.nemo-canvas-item {
    color: {{ foreground }};
}

.nemo-desktop.nemo-canvas-item:selected {
    background-color: alpha({{ accent }}, 0.8);
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Search bar
 * ===================================================================== */

searchbar,
searchbar entry {
    background-color: {{ bg_lighter }};
    color: {{ foreground }};
}

/* =====================================================================
 * Popup menus (e.g. bookmark picker)
 * ===================================================================== */

menu {
    background-color: {{ bg_light }};
    color: {{ foreground }};
    border: 1px solid {{ bg_lighter }};
}

menuitem {
    color: {{ foreground }};
}

menuitem:hover {
    background-color: {{ accent }};
    color: {{ selection_foreground }};
}

/* =====================================================================
 * Dialogs and secondary windows (preferences, properties, about)
 * ===================================================================== */

dialog,
messagedialog,
window.background {
    background-color: {{ background }};
    color: {{ bg_lighter }};
}

dialog .dialog-vbox,
messagedialog .dialog-vbox {
    background-color: {{ background }};
    color: {{ bg_lighter }};
}

dialog headerbar,
messagedialog headerbar {
    background-color: {{ bg_lighter }};
    color: {{ bg_lighter }};
}

/* General button styling for all windows */
button {
    color: {{ bg_lighter }};
}

button:hover {
    background-color: {{ accent }};
    color: {{ accent }};
}

dialog button,
messagedialog button {
    background-color: {{ bg_lighter }};
    color: {{ bg_lighter }};
    border: 1px solid {{ bg_lighter }};
}

dialog button:hover,
messagedialog button:hover {
    background-color: {{ accent }};
    color: {{ accent }};
}

dialog button.suggested-action,
messagedialog button.suggested-action {
    background-color: {{ accent }};
    color: {{ accent }};
}

/* Notebook tabs (preferences, properties) */
notebook header {
    background-color: {{ bg_lighter }};
    color: {{ bg_lighter }};
}

notebook header tab {
    color: {{ bg_lighter }};
}

notebook header tab:checked {
    background-color: {{ background }};
    color: {{ accent }};
}

notebook > stack {
    background-color: {{ background }};
    color: {{ bg_lighter }};
}

/* Stack switcher (properties dialog tabs) */
stackswitcher button {
    color: {{ bg_lighter }};
}

stackswitcher button:checked {
    color: {{ accent }};
}

/* Text views (about license, etc.) */
textview,
textview text {
    background-color: {{ background }};
    color: {{ bg_lighter }};
}

/* Entry fields */
entry {
    background-color: {{ bg_light }};
    color: {{ bg_lighter }};
    border: 1px solid {{ bg_lighter }};
}

/* Labels */
label {
    color: {{ bg_lighter }};
}

/* Check / radio buttons */
checkbutton label,
radiobutton label {
    color: {{ bg_lighter }};
}

/* Combo boxes */
combobox button {
    background-color: {{ bg_light }};
    color: {{ bg_lighter }};
    border: 1px solid {{ bg_lighter }};
}

/* Tree / list views in preferences */
treeview {
    background-color: {{ background }};
    color: {{ bg_lighter }};
}

treeview:selected {
    background-color: {{ accent }};
    color: {{ accent }};
}

/* Frames and separators */
frame > border {
    border-color: {{ bg_lighter }};
}

separator {
    background-color: {{ bg_lighter }};
}

/* Links in about dialog */
*:link,
*:visited {
    color: {{ accent }};
}

/* =====================================================================
 * Scrollbars
 * ===================================================================== */

scrollbar slider {
    background-color: {{ muted }};
}

scrollbar slider:hover {
    background-color: {{ accent }};
}
