use serde::Deserialize;
use std::process::Command;

use super::backend::DisplayBackend;
use super::monitor::{Monitor, MonitorConfig, MonitorMode};

pub struct HyprlandBackend;

impl HyprlandBackend {
    pub fn new() -> Self {
        Self
    }

    fn hyprctl(&self, args: &[&str]) -> Result<String, String> {
        let output = Command::new("hyprctl")
            .args(args)
            .output()
            .map_err(|e| format!("Failed to run hyprctl: {e}"))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(format!("hyprctl {} failed: {stderr}", args.join(" ")));
        }

        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    }
}

#[derive(Debug, Deserialize)]
struct HyprMonitor {
    id: i32,
    name: String,
    description: String,
    width: i32,
    height: i32,
    #[serde(rename = "refreshRate")]
    refresh_rate: f64,
    x: i32,
    y: i32,
    scale: f64,
    transform: i32,
    focused: bool,
    #[serde(rename = "dpmsStatus")]
    dpms_status: bool,
    disabled: bool,
    #[serde(rename = "availableModes")]
    available_modes: Vec<String>,
}

fn parse_mode(s: &str) -> Option<MonitorMode> {
    let s = s.trim_end_matches("Hz");
    let (res, hz) = s.split_once('@')?;
    let (w, h) = res.split_once('x')?;
    Some(MonitorMode {
        width: w.parse().ok()?,
        height: h.parse().ok()?,
        refresh_rate: hz.parse().ok()?,
    })
}

impl DisplayBackend for HyprlandBackend {
    fn query_monitors(&self) -> Result<Vec<Monitor>, String> {
        let json = self.hyprctl(&["monitors", "-j"])?;
        let raw: Vec<HyprMonitor> =
            serde_json::from_str(&json).map_err(|e| format!("Failed to parse monitors JSON: {e}"))?;

        let monitors = raw
            .into_iter()
            .map(|m| {
                let available_modes: Vec<MonitorMode> =
                    m.available_modes.iter().filter_map(|s| parse_mode(s)).collect();

                Monitor {
                    id: m.id,
                    name: m.name,
                    description: m.description,
                    width: m.width,
                    height: m.height,
                    refresh_rate: m.refresh_rate,
                    x: m.x,
                    y: m.y,
                    scale: m.scale,
                    transform: m.transform,
                    enabled: !m.disabled,
                    dpms: m.dpms_status,
                    focused: m.focused,
                    available_modes,
                }
            })
            .collect();

        Ok(monitors)
    }

    fn apply(&self, configs: &[MonitorConfig]) -> Result<(), String> {
        let batch: String = configs
            .iter()
            .map(|c| {
                if !c.enabled {
                    format!("keyword monitor {},disable", c.name)
                } else {
                    format!(
                        "keyword monitor {},{}x{}@{:.2},{}x{},{:.2}",
                        c.name, c.width, c.height, c.refresh_rate, c.x, c.y, c.scale,
                    )
                }
            })
            .collect::<Vec<_>>()
            .join(";");

        // Stop Eww BEFORE applying monitor changes to avoid windows appearing
        // on wrong monitors during the transition
        let _ = Command::new("bash")
            .args(["-c", "bar-ctl stop 2>/dev/null"])
            .output();

        // Apply monitor changes
        self.hyprctl(&["--batch", &batch])?;

        // Wait a moment for Hyprland to stabilize the new layout
        std::thread::sleep(std::time::Duration::from_millis(300));

        // Restart Eww AFTER monitor changes are applied and stabilized
        let _ = Command::new("bash")
            .args(["-c", "bar-ctl start 2>/dev/null"])
            .output();

        Ok(())
    }

    fn persist(&self, configs: &[MonitorConfig]) -> Result<String, String> {
        let config_dir =
            dirs::config_dir().unwrap_or_else(|| std::path::PathBuf::from("~/.config"));
        let monitors_conf = config_dir.join("hypr").join("monitors.conf");

        let mut content = String::from(
            "# Generated by settings -- edit freely, re-running settings will overwrite.\n\n",
        );

        for c in configs {
            content.push_str(&c.to_hyprland_line());
            content.push('\n');
        }

        std::fs::write(&monitors_conf, &content)
            .map_err(|e| format!("Failed to write {}: {e}", monitors_conf.display()))?;

        Ok(monitors_conf.display().to_string())
    }

    fn set_primary(&self, monitor_name: &str) -> Result<(), String> {
        self.hyprctl(&[
            "dispatch",
            "moveworkspacetomonitor",
            &format!("1 {monitor_name}"),
        ])?;
        Ok(())
    }

    fn identify(&self, monitors: &[Monitor]) -> Result<(), String> {
        for (i, m) in monitors.iter().enumerate() {
            // Write a tiny self-deleting script to /tmp so we avoid all shell
            // quoting issues when passing the command through hyprctl exec.
            let script_path = format!("/tmp/smplos-identify-{}.sh", m.name);
            let script = format!(
                "#!/bin/sh\nclear\nprintf '\\n\\n  {}  {}  \\n\\n'\nsleep 2.5\nrm -f '{}'\n",
                i + 1, m.name, script_path
            );
            if std::fs::write(&script_path, &script).is_err() { continue; }
            let _ = Command::new("chmod").args(["+x", &script_path]).output();

            // [monitor:name] tells Hyprland to open the next window from this
            // process on the named output — reliable regardless of cursor position.
            let rule = format!(
                "[float;monitor:{};size 560 180;center;noborder;rounding 14;opacity 0.9 0.9]",
                m.name
            );
            let exec_cmd = format!("{} st-wl -T smplos-identify -e {}", rule, script_path);
            let _ = self.hyprctl(&["dispatch", "exec", &exec_cmd]);
            std::thread::sleep(std::time::Duration::from_millis(120));
        }
        Ok(())
    }

    fn name(&self) -> &'static str {
        "Hyprland"
    }
}
