#!/usr/bin/env python3
"""Regenerate "smplOS Keypad Icons": a subset of Tabler Icons (outline, MIT)
with the names in icons.txt. Needs fontTools and network (or --source).

    build.py [--source DIR] [--apps SMPL_APPS_CHECKOUT]

Writes, in this repository (all committed, so builds need neither):
    src/shared/fonts/smplos-keypad-icons.ttf    the font (family "smplOS Keypad Icons")
    src/shared/fonts/keypad-icons.json          [{name, codepoint, category, tags}], icons.txt order
    src/shared/eww/pad-icons.yuck               the overlay's name -> glyph table
    src/shared/fonts/keypad-icons/LICENSE-tabler-icons.txt
--apps also copies the font, its JSON and licence into smpl-apps'
settings/ui/assets/ (Settings embeds them).
"""

import argparse
import hashlib
import io
import json
from pathlib import Path
import shutil
import tarfile
import tempfile
import urllib.request

VERSION = "3.49.0"
PACKAGES = {
    "icons-webfont": "48c69c65a5f9013d482a17cab8899a09dcaec50750d1ac7324eb63a061fffb82",
    "icons": "aa3042907eb0bdb079fd70733e2d75f785683d4726279128a0ca2343099f7074",
}
FAMILY = "smplOS Keypad Icons"
HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]


def vocabulary():
    """[(category, name)] in icons.txt order."""
    out, category = [], ""
    for line in (HERE / "icons.txt").read_text().splitlines():
        line = line.split("#")[0].strip()
        if line.startswith("["):
            category = line.strip("[]")
        elif line:
            out += [(category, name) for name in line.split()]
    names = [n for _, n in out]
    dups = sorted({n for n in names if names.count(n) > 1})
    if dups:
        raise SystemExit(f"listed twice in icons.txt: {dups}")
    return out


def fetch(source):
    if source:
        return Path(source)
    temp = Path(tempfile.mkdtemp(prefix="tabler-"))
    for package, sha in PACKAGES.items():
        url = f"https://registry.npmjs.org/@tabler/{package}/-/{package}-{VERSION}.tgz"
        data = urllib.request.urlopen(url, timeout=60).read()
        if hashlib.sha256(data).hexdigest() != sha:
            raise SystemExit(f"{url}: unexpected sha256")
        target = temp / ("wf" if package == "icons-webfont" else "ic")
        with tarfile.open(fileobj=io.BytesIO(data)) as tar:
            tar.extractall(target, filter="data")
    return temp


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", help="directory with wf/package and ic/package (extracted npm tarballs)")
    parser.add_argument("--apps", help="smpl-apps checkout to copy Settings' assets into")
    args = parser.parse_args()

    from fontTools import subset
    from fontTools.ttLib import TTFont

    source = fetch(args.source)
    meta = json.loads((source / "ic/package/icons.json").read_text())
    icons = {}
    for category, name in vocabulary():
        outline = meta.get(name, {}).get("styles", {}).get("outline")
        if not outline:
            raise SystemExit(f"Tabler {VERSION} has no outline icon '{name}'")
        icons[name] = {"codepoint": outline["unicode"], "category": category, "tags": meta[name]["tags"]}

    font = TTFont(source / "wf/package/dist/fonts/tabler-icons.ttf", recalcTimestamp=False)
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]
    options.notdef_outline = True
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=[int(i["codepoint"], 16) for i in icons.values()])
    subsetter.subset(font)
    names = font["name"]
    for record in list(names.names):
        if record.nameID in (1, 4, 16):
            record.string = FAMILY
        elif record.nameID == 6:
            record.string = FAMILY.replace(" ", "")
        elif record.nameID == 3:
            record.string = f"{FAMILY} (Tabler Icons {VERSION})"
    fonts = ROOT / "src/shared/fonts"
    font.save(fonts / "smplos-keypad-icons.ttf")

    table = {"family": FAMILY, "source": f"Tabler Icons {VERSION} (outline), MIT",
             "icons": [{"name": n, **i} for n, i in icons.items()]}
    (fonts / "keypad-icons.json").write_text(json.dumps(table, indent=1) + "\n")
    glyphs = json.dumps({n: chr(int(i["codepoint"], 16)) for n, i in icons.items()}, separators=(",", ":"))
    # ASCII \uXXXX escapes for eww's JSON parser; yuck strings eat one backslash.
    glyphs = glyphs.replace("\\", "\\\\")
    (ROOT / "src/shared/eww/pad-icons.yuck").write_text(
        ";; Generated by src/shared/fonts/keypad-icons/build.py: do not edit.\n"
        f";; Keypad icon name -> glyph in the \"{FAMILY}\" font (Tabler Icons {VERSION}, MIT).\n"
        f"(defvar pad_icons '{glyphs}')\n")
    shutil.copy(source / "wf/package/LICENSE", HERE / "LICENSE-tabler-icons.txt")

    if args.apps:
        assets = Path(args.apps) / "settings/ui/assets"
        shutil.copy(fonts / "smplos-keypad-icons.ttf", assets / "keypad-icons.ttf")
        shutil.copy(fonts / "keypad-icons.json", assets / "keypad-icons.json")
        shutil.copy(source / "wf/package/LICENSE", assets / "TABLER-ICONS-LICENSE.txt")
    print(f"{len(icons)} icons, {(fonts / 'smplos-keypad-icons.ttf').stat().st_size} bytes")


if __name__ == "__main__":
    main()
