#!/usr/bin/env python3
"""
Regenerate nemo.css for every smplOS theme from its colors.toml.

Fixes:
  - bg_lighter was wrongly used as text color (17× per file) → replaced with fg
  - accent-on-accent button hover/selected states → now use bg as text (contrast)
  - Adds tooltip styling
  - Scopes broad `button` rules so they don't fight toolbar or main-view rules

Usage:
  python3 regen-nemo-css.py
Run from the repo root or from src/. Writes in-place.
"""

import os, re, sys

THEMES_DIR = os.path.join(os.path.dirname(__file__), "shared", "themes")


def read_toml_simple(path):
    """Parse a flat key = "value" TOML file. No sections, no arrays."""
    d = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = re.match(r'^(\w+)\s*=\s*"([^"]+)"', line)
            if m:
                d[m.group(1)] = m.group(2)
    return d


def make_nemo_css(c):
    """
    c = dict from colors.toml.
    Returns a fully-formed nemo.css string with correct semantic colors.
    """
    bg        = c["background"]
    bg_l      = c["bg_light"]
    bg_ll     = c["bg_lighter"]
    fg        = c["foreground"]
    fg_dim    = c.get("fg_dim", c["foreground"])
    accent    = c["accent"]
    # selection_background = hover/selected fill colour
    # selection_foreground = text on top of that fill
    sel_bg    = c.get("selection_background", accent)
    sel_fg    = c.get("selection_foreground", bg)

    return f"""\
/* smplOS nemo theme — generated by regen-nemo-css.py */
/* Edit regen-nemo-css.py (or colors.toml), then re-run to regenerate. */

/* =====================================================================
 * If no smplOS theme is active this file is never loaded, so stock GTK
 * theming is preserved for users outside smplOS.
 * ===================================================================== */

/* =====================================================================
 * GTK named-color overrides — used by nemo's own bundled fallback CSS.
 * Must be PRIORITY_USER so they shadow active Adwaita definitions.
 * ===================================================================== */

@define-color theme_selected_bg_color {sel_bg};
@define-color theme_selected_fg_color {sel_fg};
@define-color theme_bg_color {bg};
@define-color theme_fg_color {fg};
@define-color theme_unfocused_bg_color {bg_l};
@define-color theme_unfocused_selected_bg_color alpha({sel_bg}, 0.35);
@define-color borders {bg_ll};

/* =====================================================================
 * Main window chrome
 * ===================================================================== */

.nemo-window {{
    background-color: {bg};
    color: {fg};
}}

/* =====================================================================
 * Toolbar
 * ===================================================================== */

toolbar.primary-toolbar {{
    background-color: {bg_ll};
    color: {fg};
    border-bottom: 1px solid {bg_ll};
    box-shadow: none;
}}

toolbar.primary-toolbar button,
toolbar.primary-toolbar button.flat {{
    color: {fg};
    background-color: transparent;
    border: none;
    box-shadow: none;
}}

toolbar.primary-toolbar button:hover,
toolbar.primary-toolbar button.flat:hover {{
    background-color: alpha({fg}, 0.1);
    color: {fg};
}}

toolbar.primary-toolbar button:checked,
toolbar.primary-toolbar button:active,
toolbar.primary-toolbar button.active,
toolbar.primary-toolbar button.suggested-action {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

toolbar.primary-toolbar button:checked label,
toolbar.primary-toolbar button:active label,
toolbar.primary-toolbar button.active label,
toolbar.primary-toolbar button.suggested-action label {{
    color: {sel_fg};
}}

/* =====================================================================
 * Path / breadcrumb bar
 * ===================================================================== */

.path-bar button {{
    color: {fg};
    background-color: transparent;
    border: none;
    box-shadow: none;
}}

.path-bar button:hover {{
    background-color: alpha({bg_ll}, 0.6);
    color: {fg};
}}

.path-bar button:checked,
.path-bar button:active {{
    color: {sel_fg};
    background-color: {sel_bg};
}}

/* =====================================================================
 * File list / icon grid view
 * ===================================================================== */

.nemo-window .view,
.nemo-window iconview {{
    background-color: {bg};
    color: {fg};
}}

.nemo-window .view:selected,
.nemo-window iconview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

.nemo-window .view:selected label,
.nemo-window .view:selected *,
.nemo-window iconview:selected label,
.nemo-window iconview:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Inactive F3 pane (split view)
 * ===================================================================== */

.nemo-window .nemo-inactive-pane .view:not(:selected),
.nemo-window .nemo-inactive-pane iconview {{
    background-color: {bg_l};
}}

/* =====================================================================
 * Places sidebar
 * ===================================================================== */

.sidebar,
.places-treeview {{
    background-color: {bg_l};
    color: {fg};
}}

.sidebar row:selected,
.places-treeview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

.sidebar row:selected label,
.sidebar row:selected *,
.places-treeview:selected label,
.places-treeview:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Rename / inline-entry box inside icon view
 * ===================================================================== */

.nemo-window .nemo-window-pane widget.entry {{
    border-color: {accent};
    background-color: {bg_l};
    color: {fg};
}}

.nemo-window .nemo-window-pane widget.entry:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
    border-color: {accent};
}}

/* =====================================================================
 * Floating status bar
 * ===================================================================== */

.floating-bar {{
    background-color: {accent};
    color: {sel_fg};
    border-color: {accent};
}}

/* =====================================================================
 * Drop bar (drag-over top bar)
 * ===================================================================== */

#drop-bar > revealer > box {{
    background-color: {bg_l};
    border-bottom-color: {bg_ll};
}}

/* =====================================================================
 * Desktop icon labels
 * ===================================================================== */

.nemo-desktop.nemo-canvas-item {{
    color: {fg};
}}

.nemo-desktop.nemo-canvas-item:selected {{
    background-color: alpha({sel_bg}, 0.8);
    color: {sel_fg};
}}

/* =====================================================================
 * Search bar
 * ===================================================================== */

searchbar,
searchbar entry {{
    background-color: {bg_ll};
    color: {fg};
}}

/* =====================================================================
 * Popup menus
 * ===================================================================== */

menu {{
    background-color: {bg};
    color: {fg};
    border: 1px solid {bg_ll};
}}

menuitem {{
    color: {fg};
}}

/* Match Adwaita's exact selector specificity (0,1,3) so we always win */
menu menuitem label:dir(ltr),
menu menuitem label:dir(rtl),
.menu menuitem label:dir(ltr),
.menu menuitem label:dir(rtl),
.context-menu menuitem label:dir(ltr),
.context-menu menuitem label:dir(rtl),
menuitem label {{
    color: {fg};
}}

/* Menubar top-level items (Files, Edit, View…) */
menubar > menuitem {{
    color: {fg};
}}

menubar > menuitem:hover {{
    color: {fg};
}}

menuitem:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

menuitem:hover label,
menu menuitem:hover label:dir(ltr),
menu menuitem:hover label:dir(rtl),
menuitem:hover * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Tooltips
 * ===================================================================== */

tooltip {{
    background-color: {bg_ll};
    color: {fg};
    border: 1px solid {bg_ll};
    border-radius: 4px;
    padding: 4px 8px;
}}

tooltip label {{
    color: {fg};
}}

/* =====================================================================
 * modelbutton — used by GtkPopoverMenu (dropdown / hamburger menus
 * inside dialogs and settings) — NOT covered by menuitem rules.
 * ===================================================================== */

modelbutton {{
    background-color: transparent;
    color: {fg};
}}

modelbutton label {{
    color: {fg};
}}

modelbutton:hover,
modelbutton:focus {{
    background-color: {sel_bg};
    color: {sel_fg};
    outline: none;
}}

modelbutton:hover label,
modelbutton:hover *,
modelbutton:focus label,
modelbutton:focus * {{
    color: {sel_fg};
}}

modelbutton:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

modelbutton:selected label,
modelbutton:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Listbox rows (used in settings/preferences panels)
 * ===================================================================== */

listbox {{
    background-color: {bg};
    color: {fg};
}}

listbox row {{
    background-color: transparent;
    color: {fg};
}}

listbox row:hover {{
    background-color: alpha({sel_bg}, 0.3);
    color: {fg};
}}

listbox row:selected,
listbox row:selected:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

listbox row:selected label,
listbox row:selected *,
listbox row:selected:hover label,
listbox row:selected:hover * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Text / cursor selection highlight
 * ===================================================================== */

selection {{
    background-color: alpha({sel_bg}, 0.6);
    color: {sel_fg};
}}

/* Focus outlines — use accent ring so focused items don't vanish */
button:focus,
entry:focus,
treeview:focus,
combobox:focus {{
    outline-color: {accent};
}}

/* Combobox popup rows */
combobox > window > frame > scrolledwindow > treeview row:hover,
combobox > window > frame > scrolledwindow > treeview row:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

combobox > window > frame > scrolledwindow > treeview row:hover label,
combobox > window > frame > scrolledwindow > treeview row:hover *,
combobox > window > frame > scrolledwindow > treeview row:selected label,
combobox > window > frame > scrolledwindow > treeview row:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Dialogs and secondary windows (preferences, properties, about)
 * ===================================================================== */

dialog,
messagedialog,
window.background {{
    background-color: {bg};
    color: {fg};
}}

dialog .dialog-vbox,
messagedialog .dialog-vbox {{
    background-color: {bg};
    color: {fg};
}}

dialog headerbar,
messagedialog headerbar {{
    background-color: {bg_ll};
    color: {fg};
}}

/* Scoped to dialogs/popovers so toolbar buttons keep their own hover */
dialog button,
messagedialog button,
.preferences button,
popover button {{
    background-color: {bg_l};
    color: {fg};
    border: 1px solid {bg_ll};
}}

dialog button:hover,
messagedialog button:hover,
.preferences button:hover,
popover button:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

dialog button:hover label,
dialog button:hover *,
messagedialog button:hover label,
messagedialog button:hover *,
.preferences button:hover label,
.preferences button:hover *,
popover button:hover label,
popover button:hover * {{
    color: {sel_fg};
}}

dialog button.suggested-action,
messagedialog button.suggested-action {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

dialog button.suggested-action label,
dialog button.suggested-action *,
messagedialog button.suggested-action label,
messagedialog button.suggested-action * {{
    color: {sel_fg};
}}

/* Notebook tabs (preferences, properties) */
notebook header {{
    background-color: {bg_ll};
    color: {fg};
}}

notebook header tab {{
    color: {fg};
}}

notebook header tab:checked {{
    background-color: {bg};
    color: {accent};
}}

notebook > stack {{
    background-color: {bg};
    color: {fg};
}}

/* Stack switcher (properties dialog tabs) */
stackswitcher button {{
    color: {fg};
    background-color: transparent;
}}

stackswitcher button:hover {{
    background-color: alpha({accent}, 0.15);
    color: {fg};
}}

stackswitcher button:checked {{
    color: {sel_fg};
    background-color: {sel_bg};
}}

stackswitcher button:checked label,
stackswitcher button:checked * {{
    color: {sel_fg};
}}

/* Text views (about license, etc.) */
textview,
textview text {{
    background-color: {bg};
    color: {fg};
}}

/* Entry fields in dialogs */
entry {{
    background-color: {bg_l};
    color: {fg};
    border: 1px solid {bg_ll};
}}

/* Labels */
label {{
    color: {fg};
}}

/* Check / radio buttons */
checkbutton label,
radiobutton label {{
    color: {fg};
}}

/* Combo boxes */
combobox button {{
    background-color: {bg_l};
    color: {fg};
    border: 1px solid {bg_ll};
}}

/* Tree / list views in preferences */
treeview {{
    background-color: {bg};
    color: {fg};
}}

treeview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

treeview:selected label,
treeview:selected * {{
    color: {sel_fg};
}}

/* Frames and separators */
frame > border {{
    border-color: {bg_ll};
}}

separator {{
    background-color: {bg_ll};
}}

/* Links in about dialog */
*:link,
*:visited {{
    color: {accent};
}}

/* =====================================================================
 * Scrollbars
 * ===================================================================== */

scrollbar slider {{
    background-color: {bg_ll};
}}

scrollbar slider:hover {{
    background-color: {sel_bg};
}}
"""


def main():
    themes_dir = THEMES_DIR
    themes = [d for d in os.listdir(themes_dir)
              if os.path.isdir(os.path.join(themes_dir, d))
              and not d.startswith("_")]
    themes.sort()

    ok = 0
    skip = 0
    for theme in themes:
        toml_path = os.path.join(themes_dir, theme, "colors.toml")
        css_path  = os.path.join(themes_dir, theme, "nemo.css")
        if not os.path.exists(toml_path):
            skip += 1
            continue
        try:
            c = read_toml_simple(toml_path)
            css = make_nemo_css(c)
            with open(css_path, "w") as f:
                f.write(css)
            print(f"  ✓ {theme}")
            ok += 1
        except Exception as e:
            print(f"  ✗ {theme}: {e}", file=sys.stderr)

    print(f"\n{ok} themes updated, {skip} skipped (no colors.toml).")


if __name__ == "__main__":
    main()
