#!/usr/bin/env python3
"""
Regenerate nemo.css for every smplOS theme from its colors.toml.

Fixes:
  - bg_lighter was wrongly used as text color (17× per file) → replaced with fg
  - accent-on-accent button hover/selected states → now use bg as text (contrast)
  - Adds tooltip styling
  - Scopes broad `button` rules so they don't fight toolbar or main-view rules

Run through src/regen-all-themes.sh only.
"""

import os, sys

from theme_opacity import app_background_opacity, read_colors

THEMES_DIR = os.path.join(os.path.dirname(__file__), "shared", "themes")


def read_toml_simple(path):
    """Read the canonical palette, including numeric alpha values."""
    return read_colors(path)


def contrast_ratio(first, second):
    def luminance(color):
        channels = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
        linear = [v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4
                  for v in channels]
        return sum(v * weight for v, weight in zip(linear, (0.2126, 0.7152, 0.0722)))

    values = sorted((luminance(first), luminance(second)))
    return (values[1] + 0.05) / (values[0] + 0.05)


def readable_foreground(background, preferred, *alternatives):
    for color in (preferred, *alternatives):
        if contrast_ratio(background, color) >= 4.5:
            return color
    return max(("#000000", "#ffffff"), key=lambda color: contrast_ratio(background, color))


def selection_foreground(c):
    return readable_foreground(
        c.get("selection_background", c["accent"]),
        c.get("selection_foreground", c["background"]),
        c["foreground"], c["background"],
    )


def native_alpha_css(c):
    alpha = app_background_opacity(c)
    roots = (
        ".nemo-window.smplos-native-alpha:not(.nemo-desktop-window)",
        ".nemo-quick-preview.smplos-native-alpha",
    )
    # Only structural backing surfaces clear. Controls, selected rows, media,
    # and separate menu/dialog surfaces retain their existing paint/state rules.
    children = (
        "box:not(.floating-bar)", "grid", "paned", "notebook", "notebook > header",
        "stack", "scrolledwindow", "viewport", "layout",
        ".view:not(:selected)", "iconview:not(:selected)",
        "treeview:not(:selected)", ".sidebar", ".places-treeview:not(:selected)",
        ".nemo-preview-pane", ".nemo-query-editor",
        "toolbar.primary-toolbar", "menubar", "headerbar", "searchbar",
        "textview", "textview text", "scrollbar", "scrollbar trough", "decoration",
    )
    owners = ",\n".join(roots)
    clear = ",\n".join(f"{root} {child}" for root in roots for child in children)
    labels = ",\n".join(
        f"{root} {label}" for root in roots
        for label in (".nemo-secondary-label", ".dim-label:not(:selected)")
    )
    selected_labels = ",\n".join(
        f"{root} {label}" for root in roots
        for label in (".dim-label:selected", ".view:selected .dim-label")
    )
    inactive_labels = ",\n".join(
        f"{root} .nemo-inactive-pane {label}" for root in roots
        for label in (".dim-label:selected", ".view:selected .dim-label")
    )
    return f"""
/* Native-alpha capability: one background owner, never widget opacity.
 * Old Nemo binaries lack this class and retain the opaque rules above.
 * Selections and controls are overlays; menus/dialogs remain opaque. */
{owners} {{
    background-color: alpha({c["background"]}, {alpha});
    background-image: none;
}}

{clear} {{
    background-color: transparent;
    background-image: none;
}}

{labels} {{
    opacity: 1;
    color: {c.get("fg_dim", c["foreground"])};
}}

{selected_labels} {{
    opacity: 1;
    color: {selection_foreground(c)};
}}

{inactive_labels} {{
    color: {c["foreground"]};
}}
"""


def make_nemo_css(c):
    """
    c = dict from colors.toml.
    Returns a fully-formed nemo.css string with correct semantic colors.
    """
    bg        = c["background"]
    bg_l      = c["bg_light"]
    bg_ll     = c["bg_lighter"]
    fg        = c["foreground"]
    fg_dim    = c.get("fg_dim", c["foreground"])
    accent    = c["accent"]
    # selection_background = hover/selected fill colour
    # selection_foreground = text on top of that fill
    sel_bg    = c.get("selection_background", accent)
    sel_fg    = selection_foreground(c)
    danger    = c.get("danger", c.get("accent_alt", accent))
    rounding  = c.get("rounding", "4")
    accent_fg = readable_foreground(accent, sel_fg, fg, bg)
    danger_fg = readable_foreground(danger, fg, bg)
    tab_fg    = readable_foreground(bg, accent, fg)
    disabled_fg = fg_dim if min(contrast_ratio(fg_dim, surface)
                                for surface in (bg, bg_l, bg_ll)) >= 3 else fg

    return f"""\
/* smplOS nemo theme — generated by regen-nemo-css.py */
/* Edit regen-nemo-css.py (or colors.toml), then re-run to regenerate. */

/* =====================================================================
 * If no smplOS theme is active this file is never loaded, so stock GTK
 * theming is preserved for users outside smplOS.
 * ===================================================================== */

/* =====================================================================
 * GTK named-color overrides — used by nemo's own bundled fallback CSS.
 * Must be PRIORITY_USER so they shadow active Adwaita definitions.
 * ===================================================================== */

@define-color theme_selected_bg_color {sel_bg};
@define-color theme_selected_fg_color {sel_fg};
@define-color theme_bg_color {bg};
@define-color theme_base_color {bg};
@define-color theme_fg_color {fg};
@define-color theme_text_color {fg};
@define-color theme_unfocused_bg_color {bg_l};
@define-color theme_unfocused_fg_color {fg};
@define-color theme_unfocused_base_color {bg};
@define-color theme_unfocused_text_color {fg};
@define-color theme_unfocused_selected_bg_color alpha({sel_bg}, 0.35);
@define-color theme_unfocused_selected_fg_color {fg};
@define-color borders {bg_ll};

/* =====================================================================
 * Native GTK controls, including plain GtkWindow preferences.
 * Running applications retain GTK_THEME across live theme switches.
 * Clear base-theme images as well as colors: images paint over colors.
 * Keep these defaults before the more specific Nemo chrome rules.
 * ===================================================================== */

button {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border-color: {bg_ll};
    box-shadow: none;
    text-shadow: none;
    -gtk-icon-shadow: none;
}}

button:hover,
button:active,
button:checked {{
    background-color: {bg_ll};
    color: {fg};
}}

button label,
button image,
button arrow {{
    color: inherit;
}}

button.suggested-action {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

button.destructive-action {{
    background-color: {danger};
    color: {danger_fg};
}}

entry,
spinbutton,
spinbutton entry,
scale trough,
progressbar trough,
levelbar trough,
switch {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border-color: {bg_ll};
    box-shadow: none;
}}

entry,
spinbutton entry,
textview text {{
    caret-color: {fg};
}}

headerbar,
treeview header button {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border-color: {bg_ll};
    box-shadow: none;
}}

treeview header button:hover,
treeview header button:active {{
    background-color: {bg_ll};
    color: {fg};
}}

notebook,
notebook header,
popover,
popover.background {{
    background-color: {bg};
    background-image: none;
    color: {fg};
}}

infobar,
infobar.info,
infobar.question,
infobar.warning,
infobar.error {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
}}

menuitem arrow,
menuitem accelerator,
menuitem image,
expander arrow {{
    color: inherit;
}}

check,
radio {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border-color: {fg_dim};
    box-shadow: none;
    -gtk-icon-shadow: none;
}}

check:checked,
check:indeterminate,
radio:checked,
radio:indeterminate,
switch:checked {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

switch slider,
scale slider {{
    background-color: {bg_ll};
    background-image: none;
    color: {fg};
    border-color: {fg_dim};
    box-shadow: none;
}}

scale highlight,
progressbar progress,
levelbar block.filled {{
    background-color: {sel_bg};
    background-image: none;
    border-color: {sel_bg};
}}

progressbar text,
scale value {{
    color: {fg};
}}

scrollbar,
scrollbar trough {{
    background-color: {bg};
    background-image: none;
}}

/* =====================================================================
 * Main window chrome
 * ===================================================================== */

.nemo-window {{
    background-color: {bg};
    color: {fg};
}}

/* =====================================================================
 * Menu bar (File / Edit / View …)
 * Lock bg to theme background in both focused and backdrop (unfocused)
 * states — Adwaita sets menubar:backdrop to a grey that differs from bg.
 * ===================================================================== */

menubar,
menubar:backdrop {{
    background-color: {bg};
    background-image: none;
    color: {fg};
    box-shadow: none;
}}

/* =====================================================================
 * Bottom status bar — NemoStatusBar extends GtkBox with class "toolbar".
 * Distinct from toolbar.primary-toolbar (the top toolbar).
 * ===================================================================== */

box.toolbar,
box.toolbar:backdrop {{
    background-color: {bg};
    background-image: none;
    color: {fg};
    border-top: 1px solid {bg_ll};
    box-shadow: none;
}}

box.toolbar button,
box.toolbar togglebutton {{
    color: {fg};
    background-color: transparent;
    background-image: none;
    border: none;
    box-shadow: none;
}}

box.toolbar button:hover,
box.toolbar togglebutton:hover {{
    background-color: alpha({fg}, 0.1);
    color: {fg};
}}

box.toolbar button:checked,
box.toolbar togglebutton:checked,
box.toolbar button:active,
box.toolbar togglebutton:active {{
    background-color: alpha({sel_bg}, 0.2);
    background-image: none;
    color: {fg};
    box-shadow: none;
}}

/* =====================================================================
 * Toolbar
 * ===================================================================== */

toolbar.primary-toolbar,
toolbar.primary-toolbar:backdrop {{
    background-color: {bg};
    background-image: none;
    color: {fg};
    border-bottom: 1px solid {bg_ll};
    box-shadow: none;
}}

toolbar.primary-toolbar button,
toolbar.primary-toolbar button.flat {{
    color: {fg};
    background-color: transparent;
    border: none;
    box-shadow: none;
}}

toolbar.primary-toolbar button:hover,
toolbar.primary-toolbar button.flat:hover {{
    background-color: alpha({fg}, 0.1);
    color: {fg};
}}

toolbar.primary-toolbar button:checked,
toolbar.primary-toolbar button:active,
toolbar.primary-toolbar button.active,
toolbar.primary-toolbar button.suggested-action {{
    /* Subtle tint only — keep icon at fg so symbols remain visible */
    background-color: alpha({sel_bg}, 0.2);
    color: {fg};
}}

toolbar.primary-toolbar button:checked label,
toolbar.primary-toolbar button:active label,
toolbar.primary-toolbar button.active label,
toolbar.primary-toolbar button.suggested-action label {{
    color: {fg};
}}

/* =====================================================================
 * Path / breadcrumb bar
 * ===================================================================== */

.path-bar button {{
    color: {fg};
    background-color: transparent;
    border: none;
    box-shadow: none;
}}

/* Match Adwaita .path-bar button label:dir() specificity (0,2,2) */
.path-bar button label:dir(ltr),
.path-bar button label:dir(rtl),
.path-bar button label {{
    color: {fg};
}}

.path-bar button:hover {{
    background-color: alpha({bg_ll}, 0.6);
    color: {fg};
}}

.path-bar button:hover label:dir(ltr),
.path-bar button:hover label:dir(rtl),
.path-bar button:hover label {{
    color: {fg};
}}

.path-bar button:checked,
.path-bar button:active {{
    /* Current directory: subtle tint, keep foreground text colour.
     * background-image: none clears Adwaita's button:checked
     * {{ background-image: image(#191919) }} which paints over bg-color. */
    background-color: alpha({sel_bg}, 0.2);
    background-image: none;
    color: {fg};
    box-shadow: none;
}}

.path-bar button:checked label:dir(ltr),
.path-bar button:checked label:dir(rtl),
.path-bar button:active label:dir(ltr),
.path-bar button:active label:dir(rtl),
.path-bar button:checked label,
.path-bar button:active label {{
    color: {fg};
}}

/* =====================================================================
 * File list / icon grid view
 * ===================================================================== */

.nemo-window .view,
.nemo-window iconview {{
    background-color: {bg};
    color: {fg};
}}

.nemo-window .view:selected,
.nemo-window iconview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

.nemo-window .view:selected label,
.nemo-window .view:selected *,
.nemo-window iconview:selected label,
.nemo-window iconview:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Inactive F3 pane (split view) — same background as active pane;
 * selected item gets an outline ring instead of a filled highlight.
 * ===================================================================== */

.nemo-window .nemo-inactive-pane .view:not(:selected),
.nemo-window .nemo-inactive-pane iconview {{
    background-color: {bg};
}}

.nemo-window .nemo-inactive-pane .view:selected {{
    background-color: transparent;
    color: {fg};
    outline: 2px dotted {sel_bg};
    outline-offset: -2px;
}}

.nemo-window .nemo-inactive-pane .view:selected label,
.nemo-window .nemo-inactive-pane .view:selected * {{
    color: {fg};
}}

/* =====================================================================
 * Places sidebar
 * ===================================================================== */

.sidebar,
.places-treeview {{
    background-color: {bg_l};
    color: {fg};
}}

.sidebar row:selected,
.places-treeview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

.sidebar row:selected label,
.sidebar row:selected *,
.places-treeview:selected label,
.places-treeview:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Rename / inline-entry box inside icon view
 * ===================================================================== */

.nemo-window .nemo-window-pane widget.entry {{
    border-color: {accent};
    background-color: {bg_l};
    color: {fg};
}}

.nemo-window .nemo-window-pane widget.entry:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
    border-color: {accent};
}}

/* =====================================================================
 * Floating status bar
 * ===================================================================== */

.floating-bar {{
    background-color: {accent};
    color: {accent_fg};
    border-color: {accent};
}}

.floating-bar label {{
    color: inherit;
}}

/* =====================================================================
 * Drop bar (drag-over top bar)
 * ===================================================================== */

#drop-bar > revealer > box {{
    background-color: {bg_l};
    border-bottom-color: {bg_ll};
}}

/* =====================================================================
 * Desktop icon labels
 * ===================================================================== */

.nemo-desktop.nemo-canvas-item {{
    color: {fg};
}}

.nemo-desktop.nemo-canvas-item:selected {{
    background-color: alpha({sel_bg}, 0.8);
    color: {sel_fg};
}}

/* =====================================================================
 * Quick Preview window (F3 / Space preview popup)
 * ===================================================================== */

/* Window background */
.nemo-quick-preview {{
    background-color: {bg};
    color: {fg};
}}

/* Header bar */
.nemo-quick-preview headerbar,
.nemo-quick-preview headerbar:backdrop {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border-bottom: 1px solid {bg_ll};
    box-shadow: none;
}}

.nemo-quick-preview headerbar .title {{
    color: {fg};
    font-weight: bold;
}}

.nemo-quick-preview headerbar .subtitle {{
    color: {fg_dim};
    font-size: smaller;
}}

.nemo-quick-preview headerbar label {{
    color: {fg};
}}

/* Header bar buttons (prev/next nav, fullscreen, search icon, close) */
.nemo-quick-preview headerbar button,
.nemo-quick-preview headerbar button.titlebutton {{
    background-color: transparent;
    background-image: none;
    color: {fg};
    border: none;
    box-shadow: none;
}}

.nemo-quick-preview headerbar button:hover,
.nemo-quick-preview headerbar button.titlebutton:hover {{
    background-color: {bg_ll};
    color: {fg};
}}

.nemo-quick-preview headerbar button:active,
.nemo-quick-preview headerbar button:checked {{
    background-color: {sel_bg};
    color: {sel_fg};
    box-shadow: none;
}}

.nemo-quick-preview headerbar button image,
.nemo-quick-preview headerbar button label {{
    color: inherit;
}}

/* Window decoration (shadow/rounding from WM) */
.nemo-quick-preview decoration {{
    border-radius: {rounding}px;
}}

/* Scrollbars inside the preview */
.nemo-quick-preview scrollbar {{
    background-color: {bg};
}}

.nemo-quick-preview scrollbar slider {{
    background-color: {bg_ll};
    border-radius: 4px;
    min-width: 6px;
    min-height: 6px;
}}

.nemo-quick-preview scrollbar slider:hover {{
    background-color: {fg_dim};
}}

/* Dir-analyzer / label text */
.nemo-quick-preview label {{
    color: inherit;
}}

/* Text/hex drawing area — GTK "view" class defaults to white bg in Adwaita */
.nemo-quick-preview .view,
.nemo-quick-preview textview,
.nemo-quick-preview textview text {{
    background-color: {bg};
    color: {fg};
}}

/* =====================================================================
 * Search bar (nemo file-search, top of window)
 * ===================================================================== */

searchbar,
searchbar entry {{
    background-color: {bg_ll};
    color: {fg};
}}

/* =====================================================================
 * Quick Preview in-file search bar (bottom of preview window)
 * ===================================================================== */

.nemo-quick-preview searchbar {{
    background-color: {bg_l};
    color: {fg};
    border-top: 1px solid {bg_ll};
}}

.nemo-quick-preview searchbar > revealer > box {{
    background-color: {bg_l};
}}

.nemo-quick-preview searchbar entry {{
    background-color: {bg};
    color: {fg};
    border: 1px solid {bg_ll};
    caret-color: {accent};
}}

.nemo-quick-preview searchbar entry:focus {{
    border-color: {accent};
    outline: none;
}}

.nemo-quick-preview searchbar entry selection {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

/* Prev / next match buttons */
.nemo-quick-preview searchbar button {{
    background-color: transparent;
    background-image: none;
    color: {fg};
    border: none;
    box-shadow: none;
}}

.nemo-quick-preview searchbar button:hover {{
    background-color: {bg_ll};
    color: {fg};
}}

.nemo-quick-preview searchbar button:active,
.nemo-quick-preview searchbar button:checked {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

/* "No matches" status label */
.nemo-quick-preview .search-no-match {{
    color: {danger};
    font-style: italic;
}}

/* =====================================================================
 * Popup menus
 * ===================================================================== */

menu {{
    background-color: {bg};
    color: {fg};
    border: 1px solid {bg_ll};
}}

menuitem {{
    color: {fg};
}}

/* Match Adwaita's exact selector specificity (0,1,3) so we always win */
menu menuitem label:dir(ltr),
menu menuitem label:dir(rtl),
.menu menuitem label:dir(ltr),
.menu menuitem label:dir(rtl),
.context-menu menuitem label:dir(ltr),
.context-menu menuitem label:dir(rtl),
menuitem label {{
    color: {fg};
}}

/* Menubar top-level items (Files, Edit, View…) */
menubar > menuitem {{
    color: {fg};
}}

menubar > menuitem:hover {{
    color: {fg};
}}

menuitem:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

/* High-specificity hover label rules — direct-child (>) selectors only so
 * selection_foreground does NOT cascade into popup submenus.
 * The prefixed selectors beat the (0,1,3) / (0,2,2) non-hover label rules
 * that would otherwise override the bare menuitem:hover > label rule. */
menu menuitem:hover > label:dir(ltr),
menu menuitem:hover > label:dir(rtl),
.menu menuitem:hover > label:dir(ltr),
.menu menuitem:hover > label:dir(rtl),
.context-menu menuitem:hover > label:dir(ltr),
.context-menu menuitem:hover > label:dir(rtl),
menuitem:hover > label,
menuitem:hover > box > label,
menuitem:hover > box > image,
menuitem:hover > accelerator {{
    color: {sel_fg};
}}

/* Prevent inherited hover color from reaching submenu popups.
 * menuitem:hover {{ color: sel_fg }} is inherited by all descendants — including
 * the submenu menu widget and its items.  These explicit resets undo that. */
menuitem:hover > menu,
menuitem:hover > menu menuitem {{
    background-color: {bg};
    color: {fg};
}}

menuitem:hover > menu menuitem label,
menuitem:hover > menu menuitem > box > label,
menuitem:hover > menu menuitem > box > image,
menuitem:hover > menu menuitem accelerator {{
    color: {fg};
}}

menuitem:hover > menu menuitem:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

menuitem:hover > menu menuitem:hover > label,
menuitem:hover > menu menuitem:hover > box > label,
menuitem:hover > menu menuitem:hover > box > image {{
    color: {sel_fg};
}}

/* =====================================================================
 * Tooltips
 * ===================================================================== */

tooltip {{
    background-color: {bg_ll};
    color: {fg};
    border: 1px solid {bg_ll};
    border-radius: 4px;
    padding: 4px 8px;
}}

tooltip label {{
    color: {fg};
}}

/* =====================================================================
 * modelbutton — used by GtkPopoverMenu (dropdown / hamburger menus
 * inside dialogs and settings) — NOT covered by menuitem rules.
 * ===================================================================== */

modelbutton {{
    background-color: transparent;
    color: {fg};
}}

modelbutton label {{
    color: {fg};
}}

modelbutton:hover,
modelbutton:focus {{
    background-color: {sel_bg};
    color: {sel_fg};
    outline: none;
}}

modelbutton:hover label,
modelbutton:hover *,
modelbutton:focus label,
modelbutton:focus * {{
    color: {sel_fg};
}}

modelbutton:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

modelbutton:selected label,
modelbutton:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Listbox rows (used in settings/preferences panels)
 * ===================================================================== */

listbox {{
    background-color: {bg};
    color: {fg};
}}

listbox row {{
    background-color: transparent;
    color: {fg};
}}

listbox row:hover {{
    background-color: alpha({sel_bg}, 0.15);
    color: {fg};
}}

listbox row:selected,
listbox row:selected:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

listbox row:selected label,
listbox row:selected *,
listbox row:selected:hover label,
listbox row:selected:hover * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Text / cursor selection highlight
 * ===================================================================== */

selection {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

/* Focus outlines — use accent ring so focused items don't vanish */
button:focus,
entry:focus,
treeview:focus,
combobox:focus {{
    outline-color: {accent};
}}

/* Combobox popup rows */
combobox > window > frame > scrolledwindow > treeview row:hover,
combobox > window > frame > scrolledwindow > treeview row:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

combobox > window > frame > scrolledwindow > treeview row:hover label,
combobox > window > frame > scrolledwindow > treeview row:hover *,
combobox > window > frame > scrolledwindow > treeview row:selected label,
combobox > window > frame > scrolledwindow > treeview row:selected * {{
    color: {sel_fg};
}}

/* =====================================================================
 * Dialogs and secondary windows (preferences, properties, about)
 * ===================================================================== */

dialog,
messagedialog,
window.background {{
    background-color: {bg};
    color: {fg};
}}

dialog .dialog-vbox,
messagedialog .dialog-vbox {{
    background-color: {bg};
    color: {fg};
}}

dialog headerbar,
messagedialog headerbar {{
    background-color: {bg_ll};
    color: {fg};
}}

/* Scoped to dialogs/popovers so toolbar buttons keep their own hover */
dialog button,
messagedialog button,
.preferences button,
popover button {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border: 1px solid {bg_ll};
}}

dialog button:focus,
messagedialog button:focus,
.preferences button:focus,
popover button:focus,
dialog button:active,
messagedialog button:active,
.preferences button:active,
popover button:active,
dialog button:checked,
messagedialog button:checked,
dialog button.default,
messagedialog button.default {{
    background-color: {bg_ll};
    background-image: none;
    color: {fg};
    box-shadow: none;
}}

dialog button:focus label,
dialog button:focus *,
messagedialog button:focus label,
messagedialog button:focus *,
dialog button:active label,
dialog button:active *,
messagedialog button:active label,
messagedialog button:active *,
dialog button.default label,
messagedialog button.default label {{
    color: inherit;
}}

dialog button:hover,
messagedialog button:hover,
.preferences button:hover,
popover button:hover {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

dialog button:hover label,
dialog button:hover *,
messagedialog button:hover label,
messagedialog button:hover *,
.preferences button:hover label,
.preferences button:hover *,
popover button:hover label,
popover button:hover * {{
    color: inherit;
}}

dialog button.suggested-action,
messagedialog button.suggested-action {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

dialog button.suggested-action label,
dialog button.suggested-action *,
messagedialog button.suggested-action label,
messagedialog button.suggested-action * {{
    color: inherit;
}}

/* Notebook tabs (preferences, properties) */
notebook header {{
    background-color: {bg_ll};
    color: {fg};
}}

notebook header tab {{
    background-color: transparent;
    background-image: none;
    color: {fg};
}}

notebook header tab:hover {{
    background-color: {bg_l};
}}

notebook header tab:checked {{
    background-color: {bg};
    color: {tab_fg};
}}

notebook > stack {{
    background-color: {bg};
    color: {fg};
}}

/* Stack switcher (properties dialog tabs) */
stackswitcher button {{
    color: {fg};
    background-color: transparent;
}}

stackswitcher button:hover {{
    background-color: alpha({accent}, 0.15);
    color: {fg};
}}

stackswitcher button:checked {{
    color: {sel_fg};
    background-color: {sel_bg};
}}

stackswitcher button:checked label,
stackswitcher button:checked * {{
    color: inherit;
}}

/* Text views (about license, etc.) */
textview,
textview text {{
    background-color: {bg};
    color: {fg};
}}

/* Entry fields in dialogs */
entry {{
    background-color: {bg_l};
    color: {fg};
    border: 1px solid {bg_ll};
}}

/* Labels */
label {{
    color: {fg};
}}

/* Check / radio buttons */
checkbutton label,
radiobutton label {{
    color: {fg};
}}

/* Combo boxes */
combobox button {{
    background-color: {bg_l};
    background-image: none;
    color: {fg};
    border: 1px solid {bg_ll};
}}

/* Tree / list views in preferences */
treeview {{
    background-color: {bg};
    color: {fg};
}}

iconview {{
    background-color: {bg};
    color: {fg};
}}

iconview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

treeview:selected {{
    background-color: {sel_bg};
    color: {sel_fg};
}}

treeview:selected label,
treeview:selected * {{
    color: {sel_fg};
}}

/* Frames and separators */
frame > border {{
    border-color: {bg_ll};
}}

separator {{
    background-color: {bg_ll};
}}

/* Links in about dialog */
*:link,
*:visited {{
    color: {accent};
}}

/* =====================================================================
 * Scrollbars
 * ===================================================================== */

scrollbar slider {{
    background-color: {bg_ll};
}}

scrollbar slider:hover {{
    background-color: {sel_bg};
}}

/* Disabled content stays distinct without inheriting stale dark-theme colors.
 * Backdrop intentionally keeps the same readable foreground/background pair. */
button:disabled,
button.suggested-action:disabled,
button.destructive-action:disabled,
.nemo-quick-preview headerbar button:disabled,
.nemo-quick-preview searchbar button:disabled {{
    background-color: {bg_l};
    color: {disabled_fg};
}}

button:disabled,
button:disabled label,
button:disabled image,
button:disabled arrow,
combobox:disabled button,
combobox:disabled label,
combobox:disabled arrow,
entry:disabled,
spinbutton:disabled,
checkbutton:disabled label,
radiobutton:disabled label,
menuitem:disabled,
menuitem:disabled label,
menuitem:disabled accelerator {{
    color: {disabled_fg};
    text-shadow: none;
    -gtk-icon-shadow: none;
}}
""" + native_alpha_css(c)


def main():
    themes_dir = THEMES_DIR
    themes = [d for d in os.listdir(themes_dir)
              if os.path.isdir(os.path.join(themes_dir, d))
              and not d.startswith("_")]
    themes.sort()

    ok = 0
    skip = 0
    failed = 0
    for theme in themes:
        toml_path = os.path.join(themes_dir, theme, "colors.toml")
        css_path  = os.path.join(themes_dir, theme, "nemo.css")
        if not os.path.exists(toml_path):
            skip += 1
            continue
        try:
            c = read_toml_simple(toml_path)
            css = make_nemo_css(c)
            with open(css_path, "w") as f:
                f.write(css)
            print(f"  ✓ {theme}")
            ok += 1
        except (OSError, ValueError, KeyError) as e:
            print(f"  ✗ {theme}: {e}", file=sys.stderr)
            failed += 1

    print(f"\n{ok} themes updated, {skip} skipped (no colors.toml).")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
