#!/usr/bin/env python3
"""Generate everything that lists supported keypads from registry.json.

    gen.py [--apps SMPL_APPS_CHECKOUT] [--check]

Writes (or with --check, verifies, exit 1 when stale):
    src/shared/system/udev/70-smplos-keypads.rules
    src/shared/bin/keypad-ctl              (the block between the GENERATED markers)
    SMPL_APPS/settings/src/keypad/registry.rs   with --apps
"""

import argparse
import json
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
RULES = ROOT / "src/shared/system/udev/70-smplos-keypads.rules"
KEYPAD_CTL = ROOT / "src/shared/bin/keypad-ctl"
BEGIN = "# BEGIN GENERATED by src/shared/keypads/gen.py from registry.json: do not edit.\n"
END = "# END GENERATED\n"


def load():
    reg = json.loads((HERE / "registry.json").read_text())
    for d in reg["devices"]:
        if d["status"] not in ("supported", "planned"):
            raise SystemExit(f"{d['family']}: status must be supported or planned")
        if d["status"] == "supported" and not d.get("service"):
            raise SystemExit(f"{d['family']}: a supported device needs its backend's service")
    return reg


def ids(entries):
    return [(e["vid"], p) for e in entries for p in e["pids"]]


def supported(reg):
    return [d for d in reg["devices"] if d["status"] == "supported"]


def planned(reg):
    return [d for d in reg["devices"] if d["status"] == "planned"]


def rules(reg):
    out = [
        "# Generated by src/shared/keypads/gen.py from registry.json: do not edit. See KEYPAD.md.",
        "#",
        "# Supported keypads (a working backend):",
        "# - uaccess: the seated user's backend reads the keypad (usb, hidraw, evdev)",
        "#   without the input group; Settings > Keypad reads it too.",
        "# - TAG+=\"systemd\" + SYSTEMD_ALIAS: the user manager tracks \"a supported keypad",
        f"#   is present\" as {reg['alias'].strip('/').replace('/', '-')}.device "
        f"(systemd-escape --path --suffix=device {reg['alias']}).",
        "# - SYSTEMD_USER_WANTS: plug-in starts the backend's user service; its",
        "#   BindsTo= on that device unit stops it on unplug. Nothing runs without one.",
        "# Planned keypads (no backend yet) get nothing: no access, no service, no icon.",
        "# Matches these VID:PIDs only; other keyboards are never touched.",
    ]
    for d in supported(reg):
        out += ["", f"# {d['name']} ({d['family']}): {d['backend']}"]
        for vid, pid in ids([d]):
            out.append(
                f'SUBSYSTEM=="usb", ENV{{DEVTYPE}}=="usb_device", ATTR{{idVendor}}=="{vid}", ATTR{{idProduct}}=="{pid}", '
                f'TAG+="uaccess", TAG+="systemd", ENV{{SYSTEMD_ALIAS}}="{reg["alias"]}", '
                f'ENV{{SYSTEMD_USER_WANTS}}+="{d["service"]}"')
            out.append(f'SUBSYSTEM=="hidraw", ATTRS{{idVendor}}=="{vid}", ATTRS{{idProduct}}=="{pid}", TAG+="uaccess"')
            out.append(f'SUBSYSTEM=="input", KERNEL=="event*", ATTRS{{idVendor}}=="{vid}", ATTRS{{idProduct}}=="{pid}", TAG+="uaccess"')
    if any(d.get("uinput") for d in supported(reg)):
        out += ["", "# The backend types mapped shortcuts through one virtual keyboard (uinput),",
                "# the grant the Steam and xr-workspace rules use.",
                'KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=uinput"']
    for d in planned(reg):
        out += ["", f"# Planned, no backend yet: {d['name']} ({', '.join(f'{v}:{p}' for v, p in ids([d]))})."]
    out += ["", "# Firmware update mode (ROM bootloaders): the seated user may flash a keypad",
            "# with wchisp. keypad-ctl only ever runs `wchisp info` and `wchisp flash`."]
    for b in reg["bootloaders"]:
        for vid, pid in ids([b]):
            out.append(f'SUBSYSTEM=="usb", ENV{{DEVTYPE}}=="usb_device", ATTR{{idVendor}}=="{vid}", ATTR{{idProduct}}=="{pid}", TAG+="uaccess"')
    return "\n".join(out) + "\n"


def py_block(reg):
    pad = ", ".join(f'("{v}", "{p}")' for v, p in ids(supported(reg)))
    plan = ", ".join(f'("{v}", "{p}"): "{d["name"]}"' for d in planned(reg) for v, p in ids([d]))
    boot = ", ".join(f'("{v}", "{p}")' for v, p in ids(reg["bootloaders"]))
    services = sorted({d["service"] for d in supported(reg)})
    if len(services) != 1:
        raise SystemExit("keypad-ctl knows one backend service; extend it for more")
    return (BEGIN + f"PAD_IDS = {{{pad}}}\n" + f"PLANNED_IDS = {{{plan}}}\n" + f"BOOTLOADER_IDS = {{{boot}}}\n"
            + f'SERVICE = "{services[0]}"\n' + END)


def scope(reg):
    parts = []
    for d in supported(reg):
        usb = ", ".join(f"{v}:{p}" for v, p in ids([d]))
        parts.append(f"{d['name']} (USB ID {usb}): {d['description']}")
    text = "Supports " + "; ".join(parts) + "."
    later = [d["name"] for d in planned(reg)]
    if later:
        text += f" Planned, not working yet: {', '.join(later)}."
    usb = " or ".join(f"{v}:{p}" for v, p in ids(supported(reg)))
    help_ = (f"Is yours one? Plug it in: a supported keypad shows up as connected just below. In a terminal, "
             f"keypad-ctl present (or lsusb) finds USB ID {usb}. Other keypads won't show up here.")
    return text, help_


def rust(reg):
    lit = lambda pairs: ", ".join(f'("{v}", "{p}")' for v, p in pairs)
    text, help_ = scope(reg)
    q = lambda s: json.dumps(s, ensure_ascii=False)
    return (
        "//! Generated by smplOS src/shared/keypads/gen.py from registry.json: do not edit.\n"
        "//! Supported keypads (a working backend), their bootloaders and the scope text.\n\n"
        f"pub const SUPPORTED_IDS: &[(&str, &str)] = &[{lit(ids(supported(reg)))}];\n"
        f"pub const BOOTLOADER_IDS: &[(&str, &str)] = &[{lit(ids(reg['bootloaders']))}];\n"
        f"pub const SCOPE: &str = {q(text)};\n"
        f"pub const SCOPE_HELP: &str = {q(help_)};\n"
    )


def with_block(text, block):
    if text.count(BEGIN) != 1 or text.count(END) != 1:
        raise SystemExit(f"{KEYPAD_CTL}: the GENERATED markers are missing")
    head, rest = text.split(BEGIN)
    return head + block + rest.split(END, 1)[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--apps", help="smpl-apps checkout: also write settings/src/keypad/registry.rs")
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()
    reg = load()
    outputs = {RULES: rules(reg), KEYPAD_CTL: with_block(KEYPAD_CTL.read_text(), py_block(reg))}
    if args.apps:
        outputs[Path(args.apps) / "settings/src/keypad/registry.rs"] = rust(reg)
    stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
    if args.check:
        for p in stale:
            print(f"stale: {p}", file=sys.stderr)
        return 1 if stale else 0
    for p in stale:
        p.write_text(outputs[p])
        print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
